// Package theme provides a Fyne theme that renders CJK (Chinese/Japanese/
// Korean) text. Fyne's bundled font is Latin-only, so both the app's Chinese UI
// labels and any CJK characters in file paths would otherwise show as tofu
// boxes (□). We embed a subset of Noto Sans CJK and hand it to Fyne for every
// text style, keeping all other theme attributes at their default.
package theme

import (
	_ "embed"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

// cjkFont is a subset of Noto Sans CJK (regular weight, instantiated from the
// upstream variable font) covering Latin plus common CJK ideographs, kana and
// full/half-width punctuation — enough for the UI strings and typical Chinese
// filenames without shipping the full ~30 MB face. Regenerated by the font
// subset step documented in fonts/README.md.
//
//go:embed fonts/NotoSansCJKsc-Regular-subset.otf
var cjkFont []byte

// cjkResource wraps the embedded font bytes as a Fyne resource once, so every
// Font() call returns the same object (Fyne caches on identity).
var cjkResource = fyne.NewStaticResource("NotoSansCJKsc-Regular-subset.otf", cjkFont)

// cjkTheme decorates the default theme, overriding only the font so CJK glyphs
// render. All colors, sizes and icons fall through to the base theme, so the
// app keeps Fyne's standard look and automatic light/dark adaptation.
type cjkTheme struct {
	fyne.Theme
}

// New returns a theme identical to Fyne's default except that it uses the
// embedded CJK font for all text (regular, bold, italic and monospace). We map
// every style to the one regular face: it is legible for both Latin and CJK,
// and avoids bundling four separate faces.
func New() fyne.Theme {
	return &cjkTheme{Theme: theme.DefaultTheme()}
}

// Font returns the embedded CJK face for every text style. Returning a single
// regular face for bold/italic is a deliberate size/legibility trade-off — the
// alternative (falling back to Fyne's Latin font for some styles) reintroduces
// tofu for CJK in those styles.
func (t *cjkTheme) Font(fyne.TextStyle) fyne.Resource {
	return cjkResource
}
